### ISSUE TITLE
Schedule Exporter broken :(

### ISSUE THREAD

**Issue by MNThomson** [malcolmseyd/uvic-schedule-exporter#5]
Probably due to the recent Banner upgrade. Is this gonna be updated or should I be sad?

```
Year [2022]: 
Term [Summer]: 
Log in to UVic
Username: mYuSeRnAmE
Password: 
Downloading...
Parsing...
Error fetching course data
Done. Wrote to schedule-202205.ics
```

**Comment by malcolmseyd** [comment]
This isn't going to be fixed.

I recommend using [CourseUp](https://courseup.vikelabs.ca/scheduler/)'s "Download" button if you used CourseUp this term, it does the same thing as this project without requiring any credentials.
